version: "3.8"
services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: api-final
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
    ports:
      - 8080:8080

  img:
    build:
      context: .
      dockerfile: Dockerfile
      target: img-final
    restart: always
    ports:
      - 7070:7070
volumes:
  postgres-data:
